### ISSUE TITLE
Disabling metal at runtime?

### ISSUE THREAD

**Issue by a2f0** [mybigday/llama.rn#137]
I have a question about metal - the general requirement I'm trying to support is conditionally enabling/disabling metal at runtime based on device info.

Referencing llama.rn's README.md on metal ([link](https://github.com/mybigday/llama.rn?tab=readme-ov-file#note)), it's clear that some devices support metal and others do not, however the documentation does not specify the correct way to disable it. Historically, I _think_ tweaking `n_gpu_layers` would disable metal effectively, however I do not believe this to work any more - I'm questioning whether or not it is possible to disable metal at runtime, or if it is a decision that must be made when running `pod install`.

Looking at [llamarn.podspec](https://github.com/mybigday/llama.rn/blob/main/llama-rn.podspec#L7), I see an environment variable `RNLLAMA_DISABLE_METAL` which adds some compiler flags.  If I export this variable, it looks to me like metal is effectively being disabled.

What I'm trying to do is conditionally disable metal (at runtime) in our release builds - some devices in the field might support it while others do not, and I do not want to kneecap users with metal-supported devices to accommodate those with older devices that do not support it.  Is this possible, or do I need to disable it globally for all users as part of the build process?

**Comment by a-ghorbani** [comment]
would this help? https://github.com/a-ghorbani/pocketpal-ai/blob/9956b0484929f0b3a95d009c0829452f64690c25/src/store/ModelStore.ts#L644

**Comment by a2f0** [comment]
Thanks @a-ghorbani I came across that parameter before I opened this issue, and tested it and wasn't able to get it to work.  One other thing of note is that when running the example app in the official llama.rn on a simulator, it _does_ work. This leads me to believe that metal is disabled in the example app somehow - I traced through the setup code (i.e. [bootstrap](https://github.com/mybigday/llama.rn/blob/main/scripts/bootstrap.sh)), and I don't actually see metal getting disabled anywhere, so I don't really understand how the example app is disabling metal, if it is. This consideration is what ultimately leads to my uncertainty as to whether or not it should be possible to disable metal at runtime, either with `n_gpu_layers`, `no_gpu_devices`, or some other configuration option I'm not aware of.

**Comment by jhen0409** [comment]
You can see this for understand how `no_gpu_devices` works:

https://github.com/mybigday/llama.rn/blob/01afdcc395c063b067e16d8a7a312dd0dee44123/ios/RNLlamaContext.mm#L146-L162

If `skipGpuDevices` is true (`no_gpu_devices` is true, or ggml-metal check failure), we only pick CPU device for initialization.

**Comment by a2f0** [comment]
Thanks @jhen0409, for your attention in this regard. It's still a little bit unclear to me as to the distinction of metal and the GPU.  For example, the docs [here](Metal (GPU)) specify `Metal (GPU)`, which to me suggests metal and GPU are interchangeable.  Is this the case? If it is, and I understand what you are saying correctly, `no_gpu_devices` should be sufficient to disable metal at runtime. Is there some reason that `RNLLAMA_DISABLE_METAL` in the [llama-rn.podspec](https://github.com/mybigday/llama.rn/blob/main/llama-rn.podspec) exists at all?  Is this just a convenience variable for building / debugging?

Similarly, `no_gpu_devices` does not seem to work on an iPhone 11, which has an A13 Bionic (no GPU).  When using `no_gpu_devices: true`, the model will not load, however when building with `RNLLAMA_DISABLE_METAL=1`, the model does load. Perhaps this is a bug?  The error message from the `addNativeLogListener` logs are:

```
LOG	[rnllama] [error] llama_model_load: error loading model: vector
LOG	[rnllama] [error] free_message: error loading model: gives the same error
LOG	[rnllama] [error] llama_model_load_from_file_impl: failed to load model
```

Once this becomes more clear to me I'd be happy to submit a PR to clarify the documentation in the README.md.

**Comment by a2f0** [comment]
Update: I would like to put the breaks on the potential bug report in my previous commit because I am seeing some behavior I do not understand and need to debug further.  For documentation purposes, the error I am seeing is that the model fails to load the first time (on a simulator, with `no_gpu_devices` enabled), but does _not_ fail to load when trying to load same model the second time.  With native logging enabled, the error I am receiving is very non-descript, and can be found below (these are the full logs - only three entries).  I do not have an iPhone 11 or any device without GPU support as specified in the [metal feature set table](https://developer.apple.com/metal/Metal-Feature-Set-Tables.pdf), so I have to collaborate with another one of our developers to do further testing here. Anyway, perhaps someone else is seeing a model fail to load the first time, but not the second.  I am seeing this in the most recent 0.5.9 version.

```
 LOG  [rnllama] [info] llama_model_load_from_file_impl: using device CPU (Apple M2 Pro) - 0 MiB free
 LOG  [rnllama] [error] llama_model_load: error loading model: llama_model_loader: failed to load model from /Users/a2f0/Library/Developer/CoreSimulator/Devices/0A255C32-2C32-4F0F-BBA8-98D5285EF513/data/Containers/Data/Application/6180B9FF-F2D1-4A94-B9F3-F80E8C68350A/Documents/models/Llama-3.2-1B-Instruct-Q6_K.gguf
 LOG  [rnllama] [error] llama_model_load_from_file_impl: failed to load model
```

**Comment by jhen0409** [comment]
OK, I have tried with iPhone 11 Pro Max (A13 chip), I found two problems:

1. If `no_gpu_devices` is true, we need make sure `n_gpu_layers` is 0 on this device - This may be your main question.
2. If `no_gpu_devices` is not set, the availability check is not reliable. Updated llama.cpp which made it invalid.

This may all be fixed in 708786a and release as v0.5.11. If it still breaks, please let me know.

**Comment by a2f0** [comment]
> OK, I have tried with iPhone 11 Pro Max (A13 chip), I found two problems:
> 
> 1. If `no_gpu_devices` is true, we need make sure `n_gpu_layers` is 0 on this device - This may be your main question.
> 2. If `no_gpu_devices` is not set, the availability check is not reliable. Updated llama.cpp which made it invalid.
> 
> This may all be fixed in [708786a](https://github.com/mybigday/llama.rn/commit/708786ac3d15ca8ac0d6772bfc8fc5a6855ae5e4) and release as v0.5.11. If it still breaks, please let me know.

Thanks @jhen0409 for your eyes on this. I was seeing some similar quirky behavior and struggling to capture the detail because it was somewhat difficult to describe within the context of how I thought the feature should work.  I will follow up if its still broken.
